### ISSUE TITLE
Error when use in bundle

### ISSUE THREAD

**Issue by pankti16** [brunomikoski/TMP-Text-Juicer#1]
Hello,

I am getting
```Assets\TextJuicer\Scripts\Editor\TextJuicerTransformModifierInspector.cs(6,64): error CS0246: The type or namespace name 'Editor' could not be found (are you missing a using directive or an assembly reference?)```

such errors when I am trying to build a bundle of a prefab, that have TextJuicerTransformModifier script attached.

Thanks

**Comment by Pankti16** [comment]
wrong repo.

**Comment by brunomikoski** [comment]
Just make sure your are not attaching Editor scripts into your bundle.
